server:
  host: 0.0.0.0
  port: 5000
  debug: True  # Set to False in production
models:
  detection: models/best.pt
  classification: models/cls_model.pt
paths:
  upload_folder: static/uploads
  log_folder: logs
logging:
  level: INFO
  max_size: 10485760  # 10MB
  backup_count: 5
  log_folder: logs